# Generated by Django 4.0.1 on 2022-07-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
