# Generated by Django 4.0.1 on 2022-07-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
