# Generated by Django 4.0.1 on 2022-07-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_event_date_created_event_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_updated',
        ),
    ]
