# Generated by Django 4.0.1 on 2022-07-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_event_date_created_remove_event_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='specimg',
            new_name='supervisorimg',
        ),
        migrations.AddField(
            model_name='project',
            name='projectimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectimg3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
