# Generated by Django 4.0.1 on 2022-07-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_rename_specimg_supervisor_supervisorimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='supervisorimg',
            field=models.ImageField(default='images/superimg.png', upload_to='images'),
        ),
    ]
