# Generated by Django 4.0.1 on 2022-07-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_supervisor_supervisorimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
