# Generated by Django 4.1 on 2022-08-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_student_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
