# Generated by Django 4.1 on 2022-08-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_studentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentimg',
            field=models.ImageField(default='images/superimg.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
