# Generated by Django 4.1 on 2022-08-19 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_student_studentimg_alter_studentdata_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='migrated',
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='file',
            field=models.FileField(upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
    ]
