# Generated by Django 4.1 on 2022-08-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_remove_studentdata_migrated_alter_studentdata_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='occupied',
            field=models.IntegerField(default=0),
        ),
    ]
