# Generated by Django 4.1 on 2022-09-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_general_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general_notifications',
            old_name='type',
            new_name='msgtype',
        ),
    ]
