# Generated by Django 4.1 on 2022-09-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_rename_type_general_notifications_msgtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_notifications',
            name='msgtype',
            field=models.CharField(choices=[('Supervisor', 'Supervisors'), ('Students', 'Students'), ('All', 'All')], max_length=255),
        ),
    ]
