# Generated by Django 4.1 on 2022-09-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_notifications_delete_general_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='datesent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
