# Generated by Django 4.1 on 2022-09-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_notifications_datesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='msgtype',
            field=models.CharField(blank=True, choices=[('Supervisor', 'Supervisors'), ('Students', 'Students'), ('All', 'All')], max_length=255, null=True),
        ),
    ]
