# Generated by Django 4.0.7 on 2022-09-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_alter_notifications_msgtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='msgtype',
        ),
    ]
