# Generated by Django 4.0.7 on 2022-09-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_remove_notifications_msgtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
