# Generated by Django 4.0.7 on 2022-09-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_student_email_student_verified_supervisor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='isCoordinator',
            field=models.BooleanField(default=False),
        ),
    ]
