# Generated by Django 4.0.7 on 2022-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_supervisor_iscoordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='forcoordinator',
            field=models.BooleanField(default=False),
        ),
    ]
