# Generated by Django 4.0.7 on 2022-09-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_remove_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='isCoordinator',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='role',
            field=models.CharField(choices=[('Project Coordinator', 'Project Coordinator'), ('Supervisor', 'Supervisor')], default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='title',
            field=models.CharField(choices=[('Mr', 'MR'), ('DR', 'DR'), ('PROF', 'PROF')], default='None', max_length=255),
        ),
    ]
