# Generated by Django 4.0.7 on 2022-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_rename_last_name_supervisor_other_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='title',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='rank',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='role',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
