# Generated by Django 4.0.7 on 2022-09-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_remove_supervisor_title_supervisor_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='bio',
        ),
    ]
