# Generated by Django 4.0.7 on 2022-09-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_remove_supervisor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
