# Generated by Django 4.0.7 on 2022-09-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_rename_project_group_task_project_task_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
