# Generated by Django 4.0.7 on 2022-09-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='datesent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
