# Generated by Django 4.0.7 on 2022-09-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_chatmessage_datesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
