# Generated by Django 4.0.7 on 2022-09-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_alter_project_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='specimg',
            field=models.ImageField(default='images/defaultspecimg.png', upload_to='images'),
        ),
    ]
