# Generated by Django 4.0.7 on 2022-09-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_alter_specialization_specimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
