# Generated by Django 4.0.7 on 2022-09-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_alter_specialization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreport',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
