# Generated by Django 4.0.7 on 2022-09-18 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_projectreport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='file',
            field=models.FileField(upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docs', 'docx', 'pdf', 'xlsx', 'xls', 'ppt', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='New Task', max_length=255, unique=True),
        ),
    ]
