# Generated by Django 4.0.7 on 2022-09-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_alter_event_name_alter_projectfile_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreport',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
