# Generated by Django 4.0.7 on 2022-09-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_projectreport_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='New Task', max_length=255),
        ),
    ]
