# Generated by Django 4.0.7 on 2022-09-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_alter_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='student',
        ),
    ]
