# Generated by Django 4.0.7 on 2022-09-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_remove_task_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portal.project'),
        ),
    ]
